### PR TITLE
Reset environment variables on every test suite

### PR DESCRIPTION
**Pull request by rafaljanicki**
Currently, all environment variables are set before running tests what doesn't make them isolated between tests. Such behaviour may break tests or provide incorrect values.

### CODE REVIEW

**Comment by mpuittinen** [comment]
Merged and published module version 0.5.9. Thanks for the contribution!

**Comment by rafaljanicki** [comment]
That's not all, another PR lands in a minute :)

**Comment by mpuittinen** [comment]
I changed a bit the logic how the function is determined during on('suite') to use an explicit mapping between tests and corresponding functions in case the function name == test name assumption does not apply

**Comment by rafaljanicki** [comment]
Ok, thanks.

The another PR was actually already merged as I forgot I've requested it already. Thanks for the quick release

**Pull request merged**
