### PR TITLE
Adding endpoint option to create function.

### PR DESCRIPTION
**Pull request by martinheidegger**
The usual thing that I do, when I use the very useful `create function` plugin is to add an endpoint of the same name. I thought a property that immediately adds this as well would help me.

### CODE REVIEW

**Comment by laardee** [comment]
Hi, @martinheidegger and thanks for opening this PR. I was wondering would it make sense to parameterize the endpoint method also and maybe add possibility to have multiple methods?

@mpuittinen, what do you think?

**Comment by martinheidegger** [comment]
Sorry for the late reply, how do you imagine the parameterization to work? Do you think it wouldn't be possible to add that in a later step?

**Comment by mpuittinen** [comment]
How about using the syntax which includes the method in the endpoing path (e.g. "get users", "post users")?
(see examples in https://serverless.com/framework/docs/providers/aws/events/apigateway/)

**Comment by mpuittinen** [comment]
@martinheidegger merged this with following changes:
- option is --httpEvent
- option includes the http verb (e.g. "post users", "get users", "delete users", "put users")
- fixed lint
- Updated README

Thanks for the contribution! This will be included in the next package release.

**Pull request merged**
