### PR TITLE
Support environment variables when run all tests

### PR DESCRIPTION
**Pull request by inakiabt**
It couldn't be the best way to do this because It will set all functions environment variables before start the first test.

### CODE REVIEW

**Comment by rafaljanicki** [comment]
That's a great PR, @mpuittinen could you merge this, please?

**Comment by mpuittinen** [comment]
@inakiabt I can't understand how the PR changes the functionality. SetEnvVars was moved from before getFilePaths (which should be renamed to getTestFilePaths to be more descriptive) to after it. The only thing that happens in getFilePaths is that it looks up paths to test files (in test folder) based on the lambda function names evt.options.paths. Since SetEnvVars needs the lambda function name, not the test file name (these happen to be identical), using the test file paths returned by getFilePaths is logically wrong.

**Comment by rafaljanicki** [comment]
Currently, when the tests are run without providing a function name (e.g. `sls function mocha-run`), the evt.options.paths variables is empty and therefore the SetEnvVars does not set any environment variables. However, as the getFilePaths checks for empty function arguments lists and if it's empty, gathers all files, SetEnvVars receives proper file list.

The other way to fix it is to collect filenames in SetEnvVars or move creation of promise to line 152 and reuse getFilePaths in SetEnvVars

**Comment by mpuittinen** [comment]
@rafaljanicki Thanks for the clarification, I'll see how this could be solved so that we are logically doing things right. The test folder may contain also tests created manually by the developer, i.e. it is not guaranteed that there is a 1:1 match between all test cases in the test folder and functions.

**Comment by rafaljanicki** [comment]
That's right, I just have found out that error in the PR.

**Comment by mpuittinen** [comment]
@rafaljanicki @inakiabt I'll probably fix it so, that in case that there is no functions specified in the mocha-run command, I'll check for available functions, and build the test filenames based on that. 
In case developers have tests that are not generated by this plugin / named differently / etc... there is always the option to run mocha directly.

**Comment by rafaljanicki** [comment]
I think that makes sense, thanks!

**Comment by rafaljanicki** [comment]
BTW, if you are working on this, could you also add a check on `var func = S.getProject().getFunction(funcName).toObjectPopulated(config);` if the function actually exists and throw an error? It'd look much better than `TypeError` right now :)

**Comment by mpuittinen** [comment]
This is now fixed in 0.5.7 (just out), included better handling of non-existent functions.

**Pull request closed without merging**
