### PR TITLE
Introduce configurable timeout for tests

### PR DESCRIPTION
**Pull request by rafaljanicki**

### CODE REVIEW

**Comment by rafaljanicki** [comment]
Hey @mpuittinen ,

Would you mind taking a look into this?

**Comment by mpuittinen** [comment]
I published a new version of the npm module. This fix is included there. Sorry for the delay.

**Comment by rafaljanicki** [comment]
Thanks!

**Comment by rafaljanicki** [comment]
Thanks! Should I bump up package version or will you do it?

**Comment by mpuittinen** [comment]
No need, already did it. The package version with the fix is 1.0.2

-Mikael

**Comment by rafaljanicki** [comment]
But this PR is for master, not for the v1 branch, so I guess it should be 0.5.16 version, right?

**Comment by mpuittinen** [comment]
Right. Working on two branches, sorry for the confusion. I’ve also published 0.5.16 now.

-Mikael

**Comment by rafaljanicki** [comment]
Thanks!

**Pull request merged**
